package com.example.dailypixel

import java.time.LocalDate
import kotlin.random.Random
import android.content.Context

data class Prompt(
    val text: String,
    val suitableSizes: List<Int> = listOf(8, 16, 24) // Default to all sizes
)

object DailyPrompts {
    private var context: Context? = null

    fun initialize(context: Context) {
        this.context = context
    }

    private val gridSizes = listOf(8, 16, 24)

    // Categorized prompts with size recommendations
    private val prompts = listOf(
        // SIMPLE OBJECTS (Good for 8x8)
        Prompt("A heart", listOf(8, 16)),
        Prompt("A star", listOf(8, 16)),
        Prompt("A coin", listOf(8, 16)),
        Prompt("A gem", listOf(8, 16)),
        Prompt("A key", listOf(8, 16)),
        Prompt("A lock", listOf(8, 16)),
        Prompt("A apple", listOf(8, 16)),
        Prompt("A cherry", listOf(8)),
        Prompt("A strawberry", listOf(8, 16)),
        Prompt("A banana", listOf(8, 16)),
        Prompt("A orange", listOf(8, 16)),
        Prompt("A lemon", listOf(8, 16)),
        Prompt("A grape cluster", listOf(8, 16)),
        Prompt("A watermelon slice", listOf(8, 16)),
        Prompt("A carrot", listOf(8, 16)),
        Prompt("A tomato", listOf(8, 16)),
        Prompt("A mushroom", listOf(8, 16)),
        Prompt("A egg", listOf(8)),
        Prompt("A acorn", listOf(8)),
        Prompt("A leaf", listOf(8, 16)),
        Prompt("A flower", listOf(8, 16)),
        Prompt("A snowflake", listOf(8, 16)),
        Prompt("A raindrop", listOf(8)),
        Prompt("A lightning bolt", listOf(8, 16)),
        Prompt("A sun", listOf(8, 16)),
        Prompt("A moon", listOf(8, 16)),
        Prompt("A cloud", listOf(8, 16)),
        Prompt("A diamond", listOf(8)),
        Prompt("A ruby", listOf(8)),
        Prompt("A emerald", listOf(8)),
        Prompt("A pearl", listOf(8)),
        Prompt("A ring", listOf(8)),
        Prompt("A crown", listOf(8, 16)),
        Prompt("A bomb", listOf(8, 16)),
        Prompt("A potion bottle", listOf(8, 16)),
        Prompt("A scroll", listOf(8, 16)),
        Prompt("A candle", listOf(8, 16)),
        Prompt("A feather", listOf(8, 16)),
        Prompt("A bone", listOf(8, 16)),
        Prompt("A skull", listOf(8, 16)),
        Prompt("A eye", listOf(8)),
        Prompt("A tear", listOf(8)),
        Prompt("A music note", listOf(8)),
        Prompt("A bell", listOf(8, 16)),
        Prompt("A flag", listOf(8, 16)),
        Prompt("A balloon", listOf(8, 16)),
        Prompt("A present", listOf(8, 16)),
        Prompt("A envelope", listOf(8, 16)),
        Prompt("A lightbulb", listOf(8, 16)),
        Prompt("A battery", listOf(8)),
        Prompt("A plug", listOf(8)),
        Prompt("A magnet", listOf(8)),
        Prompt("A paperclip", listOf(8)),
        Prompt("A pushpin", listOf(8)),
        Prompt("A button", listOf(8)),
        Prompt("A dice", listOf(8)),
        Prompt("A domino", listOf(8)),
        Prompt("A playing card", listOf(8, 16)),
        Prompt("A chess pawn", listOf(8)),
        Prompt("A arrow", listOf(8)),
        Prompt("A shield", listOf(8, 16)),
        Prompt("A sword", listOf(8, 16)),
        Prompt("A axe", listOf(8, 16)),
        Prompt("A hammer", listOf(8, 16)),
        Prompt("A wrench", listOf(8)),
        Prompt("A screwdriver", listOf(8)),
        Prompt("A nail", listOf(8)),
        Prompt("A screw", listOf(8)),
        Prompt("A gear", listOf(8)),
        Prompt("A spring", listOf(8)),
        Prompt("A hook", listOf(8)),
        Prompt("A chain link", listOf(8)),
        Prompt("A padlock", listOf(8)),
        Prompt("A compass", listOf(8, 16)),
        Prompt("A clock", listOf(8, 16)),
        Prompt("A hourglass", listOf(8, 16)),
        Prompt("A magnifying glass", listOf(8, 16)),
        Prompt("A telescope", listOf(8, 16)),
        Prompt("A microscope", listOf(16)),
        Prompt("A test tube", listOf(8)),
        Prompt("A beaker", listOf(8, 16)),
        Prompt("A pill", listOf(8)),
        Prompt("A syringe", listOf(8)),
        Prompt("A bandage", listOf(8)),
        Prompt("A thermometer", listOf(8)),
        Prompt("A stethoscope", listOf(16)),

        // SIMPLE FOODS (Good for 8x8 and 16x16)
        Prompt("A cookie", listOf(8, 16)),
        Prompt("A donut", listOf(8, 16)),
        Prompt("A cupcake", listOf(8, 16)),
        Prompt("A slice of cake", listOf(8, 16)),
        Prompt("A pie slice", listOf(8, 16)),
        Prompt("A bread loaf", listOf(8, 16)),
        Prompt("A croissant", listOf(8, 16)),
        Prompt("A pretzel", listOf(8, 16)),
        Prompt("A bagel", listOf(8, 16)),
        Prompt("A sandwich", listOf(8, 16)),
        Prompt("A hot dog", listOf(8, 16)),
        Prompt("A hamburger", listOf(8, 16)),
        Prompt("A taco", listOf(8, 16)),
        Prompt("A burrito", listOf(16)),
        Prompt("A slice of pizza", listOf(8, 16)),
        Prompt("A bowl of noodles", listOf(16)),
        Prompt("A sushi roll", listOf(8, 16)),
        Prompt("A rice ball", listOf(8, 16)),
        Prompt("A dumpling", listOf(8)),
        Prompt("A piece of cheese", listOf(8)),
        Prompt("A milk carton", listOf(8, 16)),
        Prompt("A coffee cup", listOf(8, 16)),
        Prompt("A teapot", listOf(16)),
        Prompt("A wine glass", listOf(8, 16)),
        Prompt("A beer mug", listOf(8, 16)),
        Prompt("A soda can", listOf(8, 16)),
        Prompt("A juice box", listOf(8, 16)),
        Prompt("A ice cream cone", listOf(8, 16)),
        Prompt("A popsicle", listOf(8, 16)),
        Prompt("A lollipop", listOf(8, 16)),
        Prompt("A candy cane", listOf(8)),
        Prompt("A chocolate bar", listOf(8)),
        Prompt("A wrapped candy", listOf(8)),
        Prompt("Popcorn", listOf(8, 16)),
        Prompt("French fries", listOf(8, 16)),
        Prompt("A drumstick", listOf(8, 16)),
        Prompt("A fish", listOf(8, 16)),
        Prompt("A bowl of soup", listOf(16)),
        Prompt("A bowl of cereal", listOf(16)),

        // MEDIUM COMPLEXITY ITEMS (Good for 16x16)
        Prompt("A tiny robot", listOf(16, 24)),
        Prompt("A computer monitor", listOf(16)),
        Prompt("A game controller", listOf(16)),
        Prompt("A smartphone", listOf(8, 16)),
        Prompt("A laptop", listOf(16)),
        Prompt("A camera", listOf(16)),
        Prompt("A television", listOf(16)),
        Prompt("A radio", listOf(16)),
        Prompt("A headphones", listOf(16)),
        Prompt("A microphone", listOf(8, 16)),
        Prompt("A speaker", listOf(8, 16)),
        Prompt("A vinyl record", listOf(8, 16)),
        Prompt("A cassette tape", listOf(8, 16)),
        Prompt("A CD", listOf(8, 16)),
        Prompt("A floppy disk", listOf(8, 16)),
        Prompt("A USB drive", listOf(8)),
        Prompt("A keyboard", listOf(16, 24)),
        Prompt("A mouse", listOf(8, 16)),
        Prompt("A joystick", listOf(16)),
        Prompt("A arcade cabinet", listOf(16, 24)),
        Prompt("A pinball machine", listOf(24)),
        Prompt("A slot machine", listOf(16, 24)),

        // ANIMALS (Various sizes)
        Prompt("A cat face", listOf(8, 16)),
        Prompt("A dog face", listOf(8, 16)),
        Prompt("A bunny", listOf(8, 16)),
        Prompt("A mouse", listOf(8, 16)),
        Prompt("A hamster", listOf(8, 16)),
        Prompt("A bird", listOf(8, 16)),
        Prompt("A chicken", listOf(8, 16)),
        Prompt("A duck", listOf(8, 16)),
        Prompt("A penguin", listOf(16)),
        Prompt("A owl", listOf(16)),
        Prompt("A eagle", listOf(16, 24)),
        Prompt("A parrot", listOf(16)),
        Prompt("A crow", listOf(16)),
        Prompt("A pigeon", listOf(8, 16)),
        Prompt("A sparrow", listOf(8)),
        Prompt("A fish", listOf(8, 16)),
        Prompt("A goldfish", listOf(8, 16)),
        Prompt("A tropical fish", listOf(16)),
        Prompt("A shark", listOf(16, 24)),
        Prompt("A whale", listOf(16, 24)),
        Prompt("A dolphin", listOf(16, 24)),
        Prompt("A octopus", listOf(16, 24)),
        Prompt("A squid", listOf(16)),
        Prompt("A jellyfish", listOf(16)),
        Prompt("A starfish", listOf(8, 16)),
        Prompt("A crab", listOf(8, 16)),
        Prompt("A lobster", listOf(16)),
        Prompt("A shrimp", listOf(8)),
        Prompt("A seahorse", listOf(16)),
        Prompt("A turtle", listOf(16)),
        Prompt("A frog", listOf(8, 16)),
        Prompt("A tadpole", listOf(8)),
        Prompt("A snake", listOf(16)),
        Prompt("A lizard", listOf(16)),
        Prompt("A gecko", listOf(8, 16)),
        Prompt("A chameleon", listOf(16)),
        Prompt("A crocodile", listOf(16, 24)),
        Prompt("A butterfly", listOf(8, 16)),
        Prompt("A bee", listOf(8)),
        Prompt("A wasp", listOf(8)),
        Prompt("A ant", listOf(8)),
        Prompt("A ladybug", listOf(8)),
        Prompt("A beetle", listOf(8)),
        Prompt("A spider", listOf(8, 16)),
        Prompt("A scorpion", listOf(16)),
        Prompt("A snail", listOf(8, 16)),
        Prompt("A worm", listOf(8)),
        Prompt("A caterpillar", listOf(8, 16)),
        Prompt("A dragonfly", listOf(8, 16)),
        Prompt("A firefly", listOf(8)),
        Prompt("A mosquito", listOf(8)),
        Prompt("A fly", listOf(8)),
        Prompt("A moth", listOf(8, 16)),
        Prompt("A grasshopper", listOf(8, 16)),
        Prompt("A cricket", listOf(8)),
        Prompt("A praying mantis", listOf(16)),
        Prompt("A fox", listOf(16, 24)),
        Prompt("A wolf", listOf(16, 24)),
        Prompt("A bear", listOf(16, 24)),
        Prompt("A panda", listOf(16, 24)),
        Prompt("A koala", listOf(16)),
        Prompt("A raccoon", listOf(16)),
        Prompt("A squirrel", listOf(8, 16)),
        Prompt("A chipmunk", listOf(8, 16)),
        Prompt("A beaver", listOf(16)),
        Prompt("A otter", listOf(16)),
        Prompt("A seal", listOf(16)),
        Prompt("A walrus", listOf(16, 24)),
        Prompt("A polar bear", listOf(16, 24)),
        Prompt("A deer", listOf(16, 24)),
        Prompt("A moose", listOf(24)),
        Prompt("A elk", listOf(24)),
        Prompt("A reindeer", listOf(16, 24)),
        Prompt("A horse", listOf(16, 24)),
        Prompt("A zebra", listOf(16, 24)),
        Prompt("A donkey", listOf(16, 24)),
        Prompt("A cow", listOf(16, 24)),
        Prompt("A bull", listOf(16, 24)),
        Prompt("A pig", listOf(16)),
        Prompt("A sheep", listOf(16)),
        Prompt("A goat", listOf(16)),
        Prompt("A llama", listOf(16, 24)),
        Prompt("A alpaca", listOf(16, 24)),
        Prompt("A camel", listOf(16, 24)),
        Prompt("A elephant", listOf(24)),
        Prompt("A rhino", listOf(24)),
        Prompt("A hippo", listOf(24)),
        Prompt("A giraffe", listOf(24)),
        Prompt("A lion", listOf(16, 24)),
        Prompt("A tiger", listOf(16, 24)),
        Prompt("A leopard", listOf(16, 24)),
        Prompt("A cheetah", listOf(16, 24)),
        Prompt("A monkey", listOf(16)),
        Prompt("A gorilla", listOf(16, 24)),
        Prompt("A chimpanzee", listOf(16, 24)),
        Prompt("A orangutan", listOf(16, 24)),
        Prompt("A sloth", listOf(16)),
        Prompt("A kangaroo", listOf(16, 24)),
        Prompt("A platypus", listOf(16)),
        Prompt("A hedgehog", listOf(8, 16)),
        Prompt("A porcupine", listOf(16)),
        Prompt("A armadillo", listOf(16)),
        Prompt("A bat", listOf(8, 16)),
        Prompt("A mole", listOf(8, 16)),
        Prompt("A badger", listOf(16)),
        Prompt("A skunk", listOf(16)),
        Prompt("A ferret", listOf(16)),
        Prompt("A weasel", listOf(16)),

        // PLANTS & NATURE (Various sizes)
        Prompt("A daisy", listOf(8, 16)),
        Prompt("A rose", listOf(16)),
        Prompt("A tulip", listOf(8, 16)),
        Prompt("A sunflower", listOf(16, 24)),
        Prompt("A lily", listOf(16)),
        Prompt("A orchid", listOf(16)),
        Prompt("A lotus", listOf(16)),
        Prompt("A dandelion", listOf(8, 16)),
        Prompt("A clover", listOf(8)),
        Prompt("A four-leaf clover", listOf(8)),
        Prompt("A fern", listOf(16)),
        Prompt("A cactus", listOf(8, 16)),
        Prompt("A succulent", listOf(8, 16)),
        Prompt("A bonsai tree", listOf(16, 24)),
        Prompt("A palm tree", listOf(16, 24)),
        Prompt("A pine tree", listOf(16, 24)),
        Prompt("A oak tree", listOf(16, 24)),
        Prompt("A willow tree", listOf(24)),
        Prompt("A cherry blossom tree", listOf(24)),
        Prompt("A bamboo", listOf(16)),
        Prompt("A grass patch", listOf(8, 16)),
        Prompt("A bush", listOf(16)),
        Prompt("A hedge", listOf(16)),
        Prompt("A vine", listOf(16)),
        Prompt("A moss", listOf(8)),
        Prompt("A mushroom cluster", listOf(16)),
        Prompt("A toadstool", listOf(8, 16)),
        Prompt("A tree stump", listOf(16)),
        Prompt("A log", listOf(16)),
        Prompt("A branch", listOf(8, 16)),
        Prompt("A twig", listOf(8)),
        Prompt("A pinecone", listOf(8)),
        Prompt("A seed", listOf(8)),
        Prompt("A sprout", listOf(8)),
        Prompt("A bud", listOf(8)),
        Prompt("A petal", listOf(8)),
        Prompt("A thorn", listOf(8)),
        Prompt("A root", listOf(16)),

        // FANTASY & MAGIC (16x16 and 24x24)
        Prompt("A wizard hat", listOf(8, 16)),
        Prompt("A magic wand", listOf(8, 16)),
        Prompt("A crystal ball", listOf(16)),
        Prompt("A spell book", listOf(16)),
        Prompt("A magic scroll", listOf(8, 16)),
        Prompt("A potion", listOf(8, 16)),
        Prompt("A cauldron", listOf(16)),
        Prompt("A crystal", listOf(8, 16)),
        Prompt("A magic gem", listOf(8, 16)),
        Prompt("A rune stone", listOf(8, 16)),
        Prompt("A amulet", listOf(8, 16)),
        Prompt("A talisman", listOf(8, 16)),
        Prompt("A magic ring", listOf(8)),
        Prompt("A enchanted sword", listOf(16)),
        Prompt("A magic staff", listOf(16, 24)),
        Prompt("A fairy", listOf(16)),
        Prompt("A pixie", listOf(16)),
        Prompt("A sprite", listOf(8, 16)),
        Prompt("A dragon", listOf(24)),
        Prompt("A baby dragon", listOf(16)),
        Prompt("A unicorn", listOf(16, 24)),
        Prompt("A pegasus", listOf(16, 24)),
        Prompt("A griffin", listOf(24)),
        Prompt("A phoenix", listOf(24)),
        Prompt("A basilisk", listOf(24)),
        Prompt("A hydra", listOf(24)),
        Prompt("A chimera", listOf(24)),
        Prompt("A cerberus", listOf(24)),
        Prompt("A sphinx", listOf(24)),
        Prompt("A minotaur", listOf(16, 24)),
        Prompt("A centaur", listOf(16, 24)),
        Prompt("A mermaid", listOf(16, 24)),
        Prompt("A kraken", listOf(24)),
        Prompt("A goblin", listOf(16)),
        Prompt("A orc", listOf(16, 24)),
        Prompt("A troll", listOf(16, 24)),
        Prompt("A ogre", listOf(16, 24)),
        Prompt("A giant", listOf(24)),
        Prompt("A dwarf", listOf(16)),
        Prompt("A elf", listOf(16, 24)),
        Prompt("A gnome", listOf(16)),
        Prompt("A leprechaun", listOf(16)),
        Prompt("A genie", listOf(16, 24)),
        Prompt("A ghost", listOf(16)),
        Prompt("A skeleton", listOf(16, 24)),
        Prompt("A zombie", listOf(16, 24)),
        Prompt("A vampire", listOf(16, 24)),
        Prompt("A werewolf", listOf(16, 24)),
        Prompt("A witch", listOf(16, 24)),
        Prompt("A wizard", listOf(16, 24)),
        Prompt("A necromancer", listOf(16, 24)),
        Prompt("A demon", listOf(16, 24)),
        Prompt("A imp", listOf(8, 16)),
        Prompt("A angel", listOf(16, 24)),
        Prompt("A cherub", listOf(16)),
        Prompt("A golem", listOf(16, 24)),
        Prompt("A elemental", listOf(16, 24)),
        Prompt("A wisp", listOf(8, 16)),
        Prompt("A spirit", listOf(16)),

        // VEHICLES & TRANSPORTATION (16x16 and 24x24)
        Prompt("A car", listOf(16, 24)),
        Prompt("A truck", listOf(16, 24)),
        Prompt("A van", listOf(16, 24)),
        Prompt("A bus", listOf(16, 24)),
        Prompt("A taxi", listOf(16, 24)),
        Prompt("A police car", listOf(16, 24)),
        Prompt("A ambulance", listOf(16, 24)),
        Prompt("A fire truck", listOf(24)),
        Prompt("A race car", listOf(16, 24)),
        Prompt("A formula one car", listOf(24)),
        Prompt("A go-kart", listOf(16)),
        Prompt("A motorcycle", listOf(16, 24)),
        Prompt("A scooter", listOf(16)),
        Prompt("A bicycle", listOf(16)),
        Prompt("A tricycle", listOf(16)),
        Prompt("A skateboard", listOf(8, 16)),
        Prompt("A roller skates", listOf(16)),
        Prompt("A train", listOf(24)),
        Prompt("A locomotive", listOf(24)),
        Prompt("A train car", listOf(16, 24)),
        Prompt("A tram", listOf(16, 24)),
        Prompt("A subway train", listOf(24)),
        Prompt("A boat", listOf(16, 24)),
        Prompt("A sailboat", listOf(16, 24)),
        Prompt("A yacht", listOf(24)),
        Prompt("A speedboat", listOf(16, 24)),
        Prompt("A canoe", listOf(16)),
        Prompt("A kayak", listOf(16)),
        Prompt("A raft", listOf(16)),
        Prompt("A ship", listOf(24)),
        Prompt("A pirate ship", listOf(24)),
        Prompt("A cruise ship", listOf(24)),
        Prompt("A cargo ship", listOf(24)),
        Prompt("A submarine", listOf(16, 24)),
        Prompt("A airplane", listOf(16, 24)),
        Prompt("A jet", listOf(16, 24)),
        Prompt("A fighter jet", listOf(24)),
        Prompt("A biplane", listOf(16, 24)),
        Prompt("A helicopter", listOf(16, 24)),
        Prompt("A hot air balloon", listOf(16, 24)),
        Prompt("A blimp", listOf(16, 24)),
        Prompt("A rocket", listOf(16, 24)),
        Prompt("A space shuttle", listOf(24)),
        Prompt("A UFO", listOf(16)),
        Prompt("A flying saucer", listOf(16)),

        // BUILDINGS & STRUCTURES (16x16 and 24x24)
        Prompt("A house", listOf(16, 24)),
        Prompt("A cottage", listOf(16, 24)),
        Prompt("A cabin", listOf(16, 24)),
        Prompt("A mansion", listOf(24)),
        Prompt("A castle", listOf(24)),
        Prompt("A tower", listOf(16, 24)),
        Prompt("A lighthouse", listOf(16, 24)),
        Prompt("A windmill", listOf(16, 24)),
        Prompt("A barn", listOf(16, 24)),
        Prompt("A silo", listOf(16, 24)),
        Prompt("A church", listOf(24)),
        Prompt("A temple", listOf(24)),
        Prompt("A mosque", listOf(24)),
        Prompt("A pagoda", listOf(24)),
        Prompt("A pyramid", listOf(24)),
        Prompt("A tent", listOf(16)),
        Prompt("A teepee", listOf(16, 24)),
        Prompt("A igloo", listOf(16)),
        Prompt("A hut", listOf(16)),
        Prompt("A treehouse", listOf(16, 24)),
        Prompt("A bridge", listOf(24)),
        Prompt("A gate", listOf(16, 24)),
        Prompt("A fence", listOf(16)),
        Prompt("A well", listOf(16)),
        Prompt("A fountain", listOf(16, 24)),
        Prompt("A statue", listOf(16, 24)),
        Prompt("A monument", listOf(24)),
        Prompt("A tombstone", listOf(16)),
        Prompt("A mailbox", listOf(8, 16)),
        Prompt("A lamp post", listOf(16)),
        Prompt("A traffic light", listOf(16)),
        Prompt("A stop sign", listOf(8, 16)),
        Prompt("A billboard", listOf(24)),
        Prompt("A bench", listOf(16)),
        Prompt("A picnic table", listOf(16, 24)),
        Prompt("A gazebo", listOf(24)),
        Prompt("A greenhouse", listOf(24)),
        Prompt("A shed", listOf(16, 24)),
        Prompt("A doghouse", listOf(16)),
        Prompt("A birdhouse", listOf(8, 16)),

        // LANDSCAPES & ENVIRONMENTS (24x24)
        Prompt("A mountain", listOf(24)),
        Prompt("A volcano", listOf(24)),
        Prompt("A hill", listOf(16, 24)),
        Prompt("A cliff", listOf(24)),
        Prompt("A cave", listOf(16, 24)),
        Prompt("A valley", listOf(24)),
        Prompt("A canyon", listOf(24)),
        Prompt("A desert", listOf(24)),
        Prompt("A oasis", listOf(24)),
        Prompt("A forest", listOf(24)),
        Prompt("A jungle", listOf(24)),
        Prompt("A meadow", listOf(24)),
        Prompt("A field", listOf(24)),
        Prompt("A farm", listOf(24)),
        Prompt("A garden", listOf(24)),
        Prompt("A park", listOf(24)),
        Prompt("A beach", listOf(24)),
        Prompt("A island", listOf(24)),
        Prompt("A lake", listOf(24)),
        Prompt("A pond", listOf(16, 24)),
        Prompt("A river", listOf(24)),
        Prompt("A waterfall", listOf(24)),
        Prompt("A ocean", listOf(24)),
        Prompt("A underwater scene", listOf(24)),
        Prompt("A coral reef", listOf(24)),
        Prompt("A city skyline", listOf(24)),
        Prompt("A village", listOf(24)),
        Prompt("A street", listOf(24)),
        Prompt("A alley", listOf(24)),
        Prompt("A marketplace", listOf(24)),
        Prompt("A harbor", listOf(24)),
        Prompt("A dock", listOf(24)),
        Prompt("A pier", listOf(24)),
        Prompt("A boardwalk", listOf(24)),
        Prompt("A path", listOf(24)),
        Prompt("A road", listOf(24)),
        Prompt("A highway", listOf(24)),
        Prompt("A tunnel", listOf(24)),
        Prompt("A cemetery", listOf(24)),
        Prompt("A ruins", listOf(24)),

        // SPACE & CELESTIAL (Various sizes)
        Prompt("A planet", listOf(16, 24)),
        Prompt("A moon", listOf(8, 16)),
        Prompt("A sun", listOf(16, 24)),
        Prompt("A star", listOf(8)),
        Prompt("A shooting star", listOf(16)),
        Prompt("A comet", listOf(16)),
        Prompt("A asteroid", listOf(16)),
        Prompt("A meteor", listOf(8, 16)),
        Prompt("A galaxy", listOf(24)),
        Prompt("A nebula", listOf(24)),
        Prompt("A black hole", listOf(24)),
        Prompt("A constellation", listOf(24)),
        Prompt("A satellite", listOf(16)),
        Prompt("A space station", listOf(24)),
        Prompt("A astronaut", listOf(16, 24)),
        Prompt("A alien", listOf(16)),
        Prompt("A space rock", listOf(8, 16)),
        Prompt("Saturn with rings", listOf(16, 24)),
        Prompt("Earth from space", listOf(16, 24)),

        // WEATHER & ATMOSPHERIC (Various sizes)
        Prompt("A rainbow", listOf(24)),
        Prompt("A tornado", listOf(24)),
        Prompt("A hurricane", listOf(24)),
        Prompt("A thunderstorm", listOf(24)),
        Prompt("A blizzard", listOf(24)),
        Prompt("A fog", listOf(24)),
        Prompt("A aurora borealis", listOf(24)),
        Prompt("A sunset", listOf(24)),
        Prompt("A sunrise", listOf(24)),
        Prompt("A eclipse", listOf(24)),

        // CLOTHING & ACCESSORIES (Various sizes)
        Prompt("A hat", listOf(8, 16)),
        Prompt("A cap", listOf(8, 16)),
        Prompt("A beanie", listOf(8, 16)),
        Prompt("A helmet", listOf(16)),
        Prompt("A crown", listOf(8, 16)),
        Prompt("A tiara", listOf(8, 16)),
        Prompt("A headband", listOf(8)),
        Prompt("A bow", listOf(8)),
        Prompt("A glasses", listOf(8, 16)),
        Prompt("A sunglasses", listOf(8, 16)),
        Prompt("A monocle", listOf(8)),
        Prompt("A mask", listOf(8, 16)),
        Prompt("A scarf", listOf(16)),
        Prompt("A necktie", listOf(8, 16)),
        Prompt("A bowtie", listOf(8)),
        Prompt("A necklace", listOf(8, 16)),
        Prompt("A pendant", listOf(8)),
        Prompt("A bracelet", listOf(8)),
        Prompt("A watch", listOf(8)),
        Prompt("A earring", listOf(8)),
        Prompt("A glove", listOf(8, 16)),
        Prompt("A mitten", listOf(8, 16)),
        Prompt("A shirt", listOf(16)),
        Prompt("A t-shirt", listOf(16)),
        Prompt("A sweater", listOf(16)),
        Prompt("A hoodie", listOf(16)),
        Prompt("A jacket", listOf(16)),
        Prompt("A coat", listOf(16)),
        Prompt("A dress", listOf(16, 24)),
        Prompt("A skirt", listOf(16)),
        Prompt("A pants", listOf(16)),
        Prompt("A shorts", listOf(16)),
        Prompt("A jeans", listOf(16)),
        Prompt("A overalls", listOf(16)),
        Prompt("A belt", listOf(8, 16)),
        Prompt("A shoe", listOf(8, 16)),
        Prompt("A sneaker", listOf(8, 16)),
        Prompt("A boot", listOf(16)),
        Prompt("A high heel", listOf(8, 16)),
        Prompt("A sandal", listOf(8, 16)),
        Prompt("A sock", listOf(8)),
        Prompt("A backpack", listOf(16)),
        Prompt("A purse", listOf(16)),
        Prompt("A suitcase", listOf(16)),
        Prompt("A umbrella", listOf(16)),

        // SPORTS & GAMES (Various sizes)
        Prompt("A soccer ball", listOf(8, 16)),
        Prompt("A basketball", listOf(8, 16)),
        Prompt("A baseball", listOf(8)),
        Prompt("A tennis ball", listOf(8)),
        Prompt("A golf ball", listOf(8)),
        Prompt("A football", listOf(8, 16)),
        Prompt("A rugby ball", listOf(8, 16)),
        Prompt("A volleyball", listOf(8, 16)),
        Prompt("A bowling ball", listOf(8, 16)),
        Prompt("A bowling pin", listOf(8, 16)),
        Prompt("A hockey puck", listOf(8)),
        Prompt("A hockey stick", listOf(16)),
        Prompt("A baseball bat", listOf(16)),
        Prompt("A tennis racket", listOf(16)),
        Prompt("A golf club", listOf(16)),
        Prompt("A ping pong paddle", listOf(8, 16)),
        Prompt("A pool cue", listOf(16)),
        Prompt("A dartboard", listOf(16)),
        Prompt("A dart", listOf(8)),
        Prompt("A target", listOf(16)),
        Prompt("A chess piece", listOf(8, 16)),
        Prompt("A checkers piece", listOf(8)),
        Prompt("A game die", listOf(8)),
        Prompt("A domino", listOf(8)),
        Prompt("A playing card", listOf(8, 16)),
        Prompt("A poker chip", listOf(8)),
        Prompt("A slot machine", listOf(16, 24)),
        Prompt("A roulette wheel", listOf(16, 24)),
        Prompt("A trophy", listOf(16)),
        Prompt("A medal", listOf(8, 16)),
        Prompt("A ribbon", listOf(8, 16)),
        Prompt("A scoreboard", listOf(16, 24)),
        Prompt("A whistle", listOf(8)),
        Prompt("A stopwatch", listOf(8, 16)),
        Prompt("A finish line", listOf(24)),

        // HOUSEHOLD ITEMS (Various sizes)
        Prompt("A chair", listOf(16)),
        Prompt("A sofa", listOf(24)),
        Prompt("A table", listOf(16, 24)),
        Prompt("A desk", listOf(16, 24)),
        Prompt("A bed", listOf(24)),
        Prompt("A pillow", listOf(8, 16)),
        Prompt("A blanket", listOf(16)),
        Prompt("A lamp", listOf(16)),
        Prompt("A chandelier", listOf(24)),
        Prompt("A fan", listOf(16)),
        Prompt("A air conditioner", listOf(16)),
        Prompt("A heater", listOf(16)),
        Prompt("A fireplace", listOf(24)),
        Prompt("A door", listOf(16, 24)),
        Prompt("A window", listOf(16)),
        Prompt("A curtain", listOf(16)),
        Prompt("A mirror", listOf(16)),
        Prompt("A picture frame", listOf(16)),
        Prompt("A vase", listOf(8, 16)),
        Prompt("A potted plant", listOf(16)),
        Prompt("A clock", listOf(16)),
        Prompt("A calendar", listOf(16)),
        Prompt("A bookshelf", listOf(16, 24)),
        Prompt("A drawer", listOf(16)),
        Prompt("A cabinet", listOf(16, 24)),
        Prompt("A wardrobe", listOf(24)),
        Prompt("A hanger", listOf(8, 16)),
        Prompt("A trash can", listOf(16)),
        Prompt("A recycling bin", listOf(16)),
        Prompt("A broom", listOf(16)),
        Prompt("A mop", listOf(16)),
        Prompt("A vacuum cleaner", listOf(16)),
        Prompt("A washing machine", listOf(16)),
        Prompt("A dryer", listOf(16)),
        Prompt("A iron", listOf(8, 16)),
        Prompt("A ironing board", listOf(16)),
        Prompt("A refrigerator", listOf(16, 24)),
        Prompt("A freezer", listOf(16)),
        Prompt("A oven", listOf(16)),
        Prompt("A stove", listOf(16)),
        Prompt("A microwave", listOf(16)),
        Prompt("A toaster", listOf(8, 16)),
        Prompt("A blender", listOf(16)),
        Prompt("A mixer", listOf(16)),
        Prompt("A coffee maker", listOf(16)),
        Prompt("A kettle", listOf(8, 16)),
        Prompt("A pot", listOf(8, 16)),
        Prompt("A pan", listOf(8, 16)),
        Prompt("A plate", listOf(8, 16)),
        Prompt("A bowl", listOf(8, 16)),
        Prompt("A cup", listOf(8)),
        Prompt("A mug", listOf(8, 16)),
        Prompt("A glass", listOf(8)),
        Prompt("A fork", listOf(8)),
        Prompt("A knife", listOf(8)),
        Prompt("A spoon", listOf(8)),
        Prompt("A chopsticks", listOf(8)),
        Prompt("A cutting board", listOf(16)),
        Prompt("A rolling pin", listOf(8, 16)),
        Prompt("A spatula", listOf(8, 16)),
        Prompt("A ladle", listOf(8, 16)),
        Prompt("A whisk", listOf(8)),
        Prompt("A can opener", listOf(8)),
        Prompt("A bottle opener", listOf(8)),
        Prompt("A corkscrew", listOf(8)),
        Prompt("A sink", listOf(16)),
        Prompt("A faucet", listOf(8, 16)),
        Prompt("A bathtub", listOf(24)),
        Prompt("A shower", listOf(16, 24)),
        Prompt("A toilet", listOf(16)),
        Prompt("A towel", listOf(16)),
        Prompt("A soap", listOf(8)),
        Prompt("A shampoo bottle", listOf(8, 16)),
        Prompt("A toothbrush", listOf(8)),
        Prompt("A toothpaste", listOf(8)),
        Prompt("A razor", listOf(8)),
        Prompt("A hairbrush", listOf(8, 16)),
        Prompt("A comb", listOf(8)),
        Prompt("A hair dryer", listOf(8, 16)),

        // MUSIC & INSTRUMENTS (Various sizes)
        Prompt("A piano", listOf(16, 24)),
        Prompt("A guitar", listOf(16)),
        Prompt("A electric guitar", listOf(16)),
        Prompt("A bass guitar", listOf(16)),
        Prompt("A ukulele", listOf(16)),
        Prompt("A violin", listOf(16)),
        Prompt("A cello", listOf(16, 24)),
        Prompt("A harp", listOf(16, 24)),
        Prompt("A drums", listOf(16, 24)),
        Prompt("A drum", listOf(8, 16)),
        Prompt("A cymbal", listOf(16)),
        Prompt("A tambourine", listOf(8, 16)),
        Prompt("A maracas", listOf(8, 16)),
        Prompt("A triangle", listOf(8)),
        Prompt("A xylophone", listOf(16)),
        Prompt("A trumpet", listOf(16)),
        Prompt("A trombone", listOf(16)),
        Prompt("A saxophone", listOf(16)),
        Prompt("A flute", listOf(8, 16)),
        Prompt("A clarinet", listOf(16)),
        Prompt("A harmonica", listOf(8)),
        Prompt("A accordion", listOf(16)),
        Prompt("A bagpipes", listOf(16)),
        Prompt("A music note", listOf(8)),
        Prompt("A treble clef", listOf(8, 16)),
        Prompt("A bass clef", listOf(8, 16)),
        Prompt("A metronome", listOf(16)),
        Prompt("A music stand", listOf(16)),
        Prompt("A microphone", listOf(8, 16)),
        Prompt("A speaker", listOf(8, 16)),
        Prompt("A headphones", listOf(16)),
        Prompt("A record player", listOf(16)),
        Prompt("A jukebox", listOf(16, 24)),

        // OFFICE & SCHOOL (Various sizes)
        Prompt("A pencil", listOf(8)),
        Prompt("A pen", listOf(8)),
        Prompt("A marker", listOf(8)),
        Prompt("A crayon", listOf(8)),
        Prompt("A paintbrush", listOf(8)),
        Prompt("A eraser", listOf(8)),
        Prompt("A pencil sharpener", listOf(8)),
        Prompt("A ruler", listOf(8, 16)),
        Prompt("A scissors", listOf(8, 16)),
        Prompt("A glue stick", listOf(8)),
        Prompt("A tape dispenser", listOf(8, 16)),
        Prompt("A stapler", listOf(8, 16)),
        Prompt("A hole punch", listOf(8, 16)),
        Prompt("A paper clip", listOf(8)),
        Prompt("A binder clip", listOf(8)),
        Prompt("A rubber band", listOf(8)),
        Prompt("A push pin", listOf(8)),
        Prompt("A thumbtack", listOf(8)),
        Prompt("A notebook", listOf(8, 16)),
        Prompt("A notepad", listOf(8, 16)),
        Prompt("A sticky note", listOf(8)),
        Prompt("A folder", listOf(8, 16)),
        Prompt("A binder", listOf(16)),
        Prompt("A clipboard", listOf(16)),
        Prompt("A calculator", listOf(8, 16)),
        Prompt("A protractor", listOf(8, 16)),
        Prompt("A compass (drawing)", listOf(8, 16)),
        Prompt("A globe", listOf(16)),
        Prompt("A map", listOf(16, 24)),
        Prompt("A chalkboard", listOf(16, 24)),
        Prompt("A whiteboard", listOf(16, 24)),
        Prompt("A projector", listOf(16)),
        Prompt("A printer", listOf(16)),
        Prompt("A scanner", listOf(16)),
        Prompt("A photocopier", listOf(16, 24)),
        Prompt("A fax machine", listOf(16)),
        Prompt("A typewriter", listOf(16)),
        Prompt("A briefcase", listOf(16)),
        Prompt("A filing cabinet", listOf(16, 24)),

        // INTERPRETABLE PROMPTS (Various sizes)
        Prompt("Something sweet", listOf(8, 16, 24)),
        Prompt("Something sour", listOf(8, 16, 24)),
        Prompt("Something spicy", listOf(8, 16, 24)),
        Prompt("Something cold", listOf(8, 16, 24)),
        Prompt("Something hot", listOf(8, 16, 24)),
        Prompt("Something soft", listOf(8, 16, 24)),
        Prompt("Something hard", listOf(8, 16, 24)),
        Prompt("Something round", listOf(8, 16, 24)),
        Prompt("Something square", listOf(8, 16, 24)),
        Prompt("Something triangular", listOf(8, 16, 24)),
        Prompt("Something tiny", listOf(8)),
        Prompt("Something huge", listOf(24)),
        Prompt("Something fast", listOf(8, 16, 24)),
        Prompt("Something slow", listOf(8, 16, 24)),
        Prompt("Something bright", listOf(8, 16, 24)),
        Prompt("Something dark", listOf(8, 16, 24)),
        Prompt("Something colorful", listOf(8, 16, 24)),
        Prompt("Something monochrome", listOf(8, 16, 24)),
        Prompt("Something happy", listOf(8, 16, 24)),
        Prompt("Something sad", listOf(8, 16, 24)),
        Prompt("Something scary", listOf(8, 16, 24)),
        Prompt("Something cute", listOf(8, 16, 24)),
        Prompt("Something funny", listOf(8, 16, 24)),
        Prompt("Something mysterious", listOf(8, 16, 24)),
        Prompt("Something ancient", listOf(8, 16, 24)),
        Prompt("Something futuristic", listOf(8, 16, 24)),
        Prompt("Something natural", listOf(8, 16, 24)),
        Prompt("Something artificial", listOf(8, 16, 24)),
        Prompt("Something flying", listOf(8, 16, 24)),
        Prompt("Something swimming", listOf(8, 16, 24)),
        Prompt("Something underground", listOf(8, 16, 24)),
        Prompt("Something floating", listOf(8, 16, 24)),
        Prompt("Something glowing", listOf(8, 16, 24)),
        Prompt("Something shiny", listOf(8, 16, 24)),
        Prompt("Something rusty", listOf(8, 16, 24)),
        Prompt("Something broken", listOf(8, 16, 24)),
        Prompt("Something new", listOf(8, 16, 24)),
        Prompt("Something old", listOf(8, 16, 24)),
        Prompt("A cozy place", listOf(16, 24)),
        Prompt("A scary place", listOf(16, 24)),
        Prompt("A peaceful scene", listOf(24)),
        Prompt("A chaotic scene", listOf(24)),
        Prompt("A celebration", listOf(16, 24)),
        Prompt("A disaster", listOf(24)),
        Prompt("A dream", listOf(16, 24)),
        Prompt("A nightmare", listOf(16, 24)),
        Prompt("A memory", listOf(16, 24)),
        Prompt("A wish", listOf(16, 24)),
        Prompt("Your favorite food", listOf(8, 16, 24)),
        Prompt("Your favorite animal", listOf(8, 16, 24)),
        Prompt("Your favorite place", listOf(16, 24)),
        Prompt("Your favorite thing", listOf(8, 16, 24)),
        Prompt("Your mood today", listOf(8, 16, 24)),
        Prompt("The weather outside", listOf(16, 24)),
        Prompt("A childhood toy", listOf(8, 16, 24)),
        Prompt("A special item", listOf(8, 16, 24)),
        Prompt("A lucky charm", listOf(8, 16)),
        Prompt("A power-up", listOf(8, 16)),
        Prompt("A treasure", listOf(8, 16, 24)),
        Prompt("A tool", listOf(8, 16)),
        Prompt("A weapon", listOf(8, 16)),
        Prompt("A shield", listOf(8, 16)),
        Prompt("A portal", listOf(16, 24)),
        Prompt("A door to somewhere", listOf(16, 24)),
        Prompt("A window view", listOf(16, 24)),
        Prompt("A reflection", listOf(16, 24)),
        Prompt("A shadow", listOf(8, 16, 24)),
        Prompt("A silhouette", listOf(8, 16, 24)),
        Prompt("A pattern", listOf(8, 16, 24)),
        Prompt("A texture", listOf(8, 16, 24)),
        Prompt("An emotion", listOf(8, 16, 24)),
        Prompt("A sound", listOf(8, 16, 24)),
        Prompt("A smell", listOf(8, 16, 24)),
        Prompt("A taste", listOf(8, 16, 24)),
        Prompt("A feeling", listOf(8, 16, 24)),
        Prompt("A season", listOf(16, 24)),
        Prompt("A holiday symbol", listOf(8, 16, 24)),
        Prompt("A time of day", listOf(16, 24)),
        Prompt("A weather phenomenon", listOf(16, 24)),
        Prompt("A natural element", listOf(8, 16, 24)),
        Prompt("A piece of nature", listOf(8, 16, 24)),
        Prompt("A tiny world", listOf(16, 24)),
        Prompt("A mini landscape", listOf(24)),
        Prompt("A micro ecosystem", listOf(24)),
        Prompt("A small adventure", listOf(16, 24)),
        Prompt("A quiet moment", listOf(16, 24)),
        Prompt("A busy scene", listOf(24)),
        Prompt("A hidden secret", listOf(8, 16, 24)),
        Prompt("A lost item", listOf(8, 16, 24)),
        Prompt("A found treasure", listOf(8, 16, 24)),
        Prompt("A gift", listOf(8, 16, 24)),
        Prompt("A surprise", listOf(8, 16, 24)),
        Prompt("A mystery", listOf(8, 16, 24)),
        Prompt("A clue", listOf(8, 16, 24)),
        Prompt("A sign", listOf(8, 16, 24)),
        Prompt("A symbol", listOf(8, 16, 24)),
        Prompt("A logo", listOf(8, 16)),
        Prompt("A badge", listOf(8, 16)),
        Prompt("A flag design", listOf(16, 24)),
        Prompt("A coat of arms", listOf(16, 24)),
        Prompt("A mandala", listOf(16, 24)),
        Prompt("A maze", listOf(16, 24)),
        Prompt("A puzzle piece", listOf(8, 16)),
        Prompt("A game board", listOf(24)),
        Prompt("A map fragment", listOf(16, 24)),
        Prompt("A constellation", listOf(24)),
        Prompt("A zodiac sign", listOf(16, 24)),
        Prompt("A rune", listOf(8, 16)),
        Prompt("A hieroglyph", listOf(8, 16)),
        Prompt("An emoji", listOf(8, 16)),
        Prompt("A pixel art classic", listOf(8, 16, 24))
    )

    fun getTodaysPrompt(): String {
        val today = LocalDate.now()
        val promptAndSize = getPromptForDate(today)
        return promptAndSize.first.text
    }

    fun getPromptForDate(date: LocalDate): Pair<Prompt, Int> {
        val dateSeed = date.year * 10000 + date.monthValue * 100 + date.dayOfMonth
        val random = Random(dateSeed.toLong())

        // First pick a prompt
        val prompt = prompts[random.nextInt(prompts.size)]

        // Then pick a suitable size for that prompt
        val suitableSize = prompt.suitableSizes[random.nextInt(prompt.suitableSizes.size)]

        return Pair(prompt, suitableSize)
    }

    fun getTodaysGridSize(): Int {
        val today = LocalDate.now()
        return getGridSizeForDate(today)
    }

    fun getGridSizeForDate(date: LocalDate): Int {
        val promptAndSize = getPromptForDate(date)
        return promptAndSize.second
    }
}